// <auto-generated />
using System;
using DispenserProvider.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DispenserProvider.DataBase.Migrations
{
    [DbContext(typeof(DispenserContext))]
    [Migration("20250813113611_Postgres-Init")]
    partial class PostgresInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DispenserProvider.DataBase.Models.BuilderDTO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FinishTime")
                        .HasPrecision(0)
                        .HasColumnType("timestamptz");

                    b.Property<string>("ProviderAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)");

                    b.Property<DateTime?>("StartTime")
                        .HasPrecision(0)
                        .HasColumnType("timestamptz");

                    b.Property<long>("TransactionDetailId")
                        .HasColumnType("bigint");

                    b.Property<string>("WeiAmount")
                        .IsRequired()
                        .HasMaxLength(78)
                        .HasColumnType("character varying(78)");

                    b.HasKey("Id");

                    b.HasIndex("TransactionDetailId");

                    b.ToTable("Builders");
                });

            modelBuilder.Entity("DispenserProvider.DataBase.Models.DispenserDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CreationLogSignature")
                        .IsRequired()
                        .HasMaxLength(132)
                        .HasColumnType("character varying(132)");

                    b.Property<string>("DeletionLogSignature")
                        .HasMaxLength(132)
                        .HasColumnType("character varying(132)");

                    b.Property<long?>("RefundDetailId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RefundFinishTime")
                        .HasPrecision(0)
                        .HasColumnType("timestamptz");

                    b.Property<long>("WithdrawalDetailId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreationLogSignature");

                    b.HasIndex("DeletionLogSignature");

                    b.HasIndex("RefundDetailId")
                        .IsUnique();

                    b.HasIndex("WithdrawalDetailId")
                        .IsUnique();

                    b.ToTable("Dispenser");
                });

            modelBuilder.Entity("DispenserProvider.DataBase.Models.LogDTO", b =>
                {
                    b.Property<string>("Signature")
                        .HasMaxLength(132)
                        .HasColumnType("character varying(132)");

                    b.Property<DateTime>("CreationTime")
                        .HasPrecision(0)
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsCreation")
                        .HasColumnType("boolean");

                    b.HasKey("Signature");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DispenserProvider.DataBase.Models.SignatureDTO", b =>
                {
                    b.Property<string>("Signature")
                        .HasMaxLength(132)
                        .HasColumnType("character varying(132)");

                    b.Property<string>("DispenserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("ValidUntil")
                        .HasPrecision(0)
                        .HasColumnType("timestamptz");

                    b.HasKey("Signature");

                    b.HasIndex("DispenserId");

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("DispenserProvider.DataBase.Models.TakenTrackDTO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DispenserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DispenserId")
                        .IsUnique();

                    b.ToTable("TakenTrack");
                });

            modelBuilder.Entity("DispenserProvider.DataBase.Models.TransactionDetailDTO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChainId")
                        .HasColumnType("bigint");

                    b.Property<long>("PoolId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)");

                    b.HasKey("Id");

                    b.HasIndex("UserAddress", "ChainId", "PoolId")
                        .IsUnique();

                    b.ToTable("TransactionDetails");
                });

            modelBuilder.Entity("DispenserProvider.DataBase.Models.BuilderDTO", b =>
                {
                    b.HasOne("DispenserProvider.DataBase.Models.TransactionDetailDTO", "TransactionDetail")
                        .WithMany("Builders")
                        .HasForeignKey("TransactionDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionDetail");
                });

            modelBuilder.Entity("DispenserProvider.DataBase.Models.DispenserDTO", b =>
                {
                    b.HasOne("DispenserProvider.DataBase.Models.LogDTO", "CreationLog")
                        .WithMany("CreationDispensers")
                        .HasForeignKey("CreationLogSignature")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DispenserProvider.DataBase.Models.LogDTO", "DeletionLog")
                        .WithMany("DeletionDispensers")
                        .HasForeignKey("DeletionLogSignature")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DispenserProvider.DataBase.Models.TransactionDetailDTO", "RefundDetail")
                        .WithOne("RefundDispenser")
                        .HasForeignKey("DispenserProvider.DataBase.Models.DispenserDTO", "RefundDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DispenserProvider.DataBase.Models.TransactionDetailDTO", "WithdrawalDetail")
                        .WithOne("WithdrawalDispenser")
                        .HasForeignKey("DispenserProvider.DataBase.Models.DispenserDTO", "WithdrawalDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreationLog");

                    b.Navigation("DeletionLog");

                    b.Navigation("RefundDetail");

                    b.Navigation("WithdrawalDetail");
                });

            modelBuilder.Entity("DispenserProvider.DataBase.Models.SignatureDTO", b =>
                {
                    b.HasOne("DispenserProvider.DataBase.Models.DispenserDTO", "Dispenser")
                        .WithMany("UserSignatures")
                        .HasForeignKey("DispenserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dispenser");
                });

            modelBuilder.Entity("DispenserProvider.DataBase.Models.TakenTrackDTO", b =>
                {
                    b.HasOne("DispenserProvider.DataBase.Models.DispenserDTO", "Dispenser")
                        .WithOne("TakenTrack")
                        .HasForeignKey("DispenserProvider.DataBase.Models.TakenTrackDTO", "DispenserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dispenser");
                });

            modelBuilder.Entity("DispenserProvider.DataBase.Models.DispenserDTO", b =>
                {
                    b.Navigation("TakenTrack");

                    b.Navigation("UserSignatures");
                });

            modelBuilder.Entity("DispenserProvider.DataBase.Models.LogDTO", b =>
                {
                    b.Navigation("CreationDispensers");

                    b.Navigation("DeletionDispensers");
                });

            modelBuilder.Entity("DispenserProvider.DataBase.Models.TransactionDetailDTO", b =>
                {
                    b.Navigation("Builders");

                    b.Navigation("RefundDispenser");

                    b.Navigation("WithdrawalDispenser");
                });
#pragma warning restore 612, 618
        }
    }
}
