name: Deploy and Update on Release
on:
  release:
    types:
      - published
permissions:
  packages: write
  contents: write
  pull-requests: write
  id-token: write

jobs:
  deploy_and_update:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build
        run: |
          dotnet restore
          dotnet build -c Release

      - name: Get Release Info
        id: get_release_info
        shell: bash
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VERSION=${TAG#v}
          VERSION=${VERSION%%-*}
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version extracted: $VERSION"

      - name: Update .csproj with version and release notes
        if: contains(env.TAG, '-stage')
        shell: pwsh
        run: |
          $version = "${{ env.VERSION }}"
          $tag = "${{ env.TAG }}"
          $repository = "${{ github.repository }}"
          Write-Host "Updating .csproj with version $version and PackageReleaseNotes"
          [xml]$csproj = Get-Content -Path ./src/DispenserProvider.DataBase/DispenserProvider.DataBase.csproj
          $csproj.Project.PropertyGroup.Version = $version
          $releaseNotes = "https://github.com/$repository/releases/tag/v$version-prod"
          $csproj.Project.PropertyGroup.PackageReleaseNotes = $releaseNotes
          $csproj.Save("$(PWD)/src/DispenserProvider.DataBase/DispenserProvider.DataBase.csproj")

      - name: Create Pull Request
        if: contains(env.TAG, '-stage')
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update project version and release notes
          title: "Update project version to ${{ env.VERSION }}"
          body: "This PR updates the .csproj project version to ${{ env.VERSION }} and updates package release notes."
          branch: "update-version-${{ env.VERSION }}"
          delete-branch: true
          add-paths: ./src/DispenserProvider.DataBase/DispenserProvider.DataBase.csproj

      - name: Merge Pull Request
        if: contains(env.TAG, '-stage') && steps.create_pr.outputs.pull-request-number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number="${{ steps.create_pr.outputs.pull-request-number }}"
          echo "pr_number=$pr_number"
          curl \
            -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/merge" \
            -d '{"merge_method": "squash"}'

      - name: Select target DB host
        id: select_db
        run: |
          if [[ "${{ env.TAG }}" == *"-stage"* ]]; then
            echo "db_host=${{ secrets.STAGE_DB_HOST }}" >> "$GITHUB_OUTPUT"
            echo "env_name=stage" >> "$GITHUB_OUTPUT"
          elif [[ "${{ env.TAG }}" == *"-prod"* ]]; then
            echo "db_host=${{ secrets.PROD_DB_HOST }}" >> "$GITHUB_OUTPUT"
            echo "env_name=prod" >> "$GITHUB_OUTPUT"
          fi

      - name: Install dotnet-ef
        run: |
          dotnet tool install --global dotnet-ef --version 8.0.14
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Download RDS CA bundle
        run: curl -sSLo rds-ca.pem https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Generate IAM DB auth token
        id: token_generation
        env:
          DB_HOST: ${{ steps.select_db.outputs.db_host }}
          DB_USER: ${{ secrets.DB_USER }}
        run: |
          TOKEN=$(aws rds generate-db-auth-token \
            --hostname "$DB_HOST" \
            --port 5432 \
            --region "$AWS_REGION" \
            --username "$DB_USER")
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

      - name: Deploy EF Core Migrations
        if: ${{ steps.select_db.outputs.db_host != '' }}
        env:
          CONFIGUREDSQLCONNECTION_ACTION_CONNECTION: >-
            Host=${{ steps.select_db.outputs.db_host }};
            Port=5432;
            Database=${{ secrets.DB_NAME }};
            Username=${{ secrets.DB_USER }};
            Password=${{ steps.token_generation.outputs.token }};
            SSL Mode=VerifyFull;
            Root Certificate=${{ github.workspace }}/rds-ca.pem
        run: |
          dotnet ef database update -c DispenserContext -p ./src/DispenserProvider.Migrations/DispenserProvider.Migrations.csproj -s ./src/DispenserProvider.Migrations/DispenserProvider.Migrations.csproj

      - name: Package and Push NuGet Package to GitHub Packages
        if: contains(env.TAG, '-prod')
        run: |
          dotnet pack ./src/DispenserProvider.DataBase/DispenserProvider.DataBase.csproj --configuration Release --output nupkg/
          dotnet nuget push nupkg/*.nupkg --source https://nuget.pkg.github.com/The-Poolz/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
